_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 49
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
